FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    git=1:2.34.1-1ubuntu1.9 \
    python3=3.10.6-1~22.04 \
    python3-pip=22.0.2+dfsg-1ubuntu0.2 \
    openssh-server=1:8.9p1-3ubuntu0.1

RUN git clone https://github.com/moevm/devops-examples.git
WORKDIR devops-examples/EXAMPLE_APP

ADD ./app-req.txt requirements.txt

ENV FLASK_APP main.py
ENV FLASK_RUN_HOST 0.0.0.0

RUN pip3 install -r requirements.txt

ENTRYPOINT ["flask", "run", "--host=0.0.0.0"]