version: "3"
services:
    app:
        env_file:
            - .env
        ports:
            -   "${PORT}:5000"
        build: 
            dockerfile: Dockerfile_app
            context: ./app
        deploy:
            resources:
                limits:
                    memory: 110M

    tester:
        build: 
            dockerfile: Dockerfile_tester
            context: ./tester
        depends_on:
            - app
        volumes:
        - ./logs:/logs